spring.application.name=spring-web-mvc
server.port=8383

# DB1: H2 Configuration
spring.datasource.db1.jdbc-url=jdbc:h2:mem:varun
spring.datasource.db1.driver-class-name=org.h2.Driver
spring.datasource.db1.username=sa
spring.datasource.db1.password=

# DB2: PostgreSQL Configuration
spring.datasource.db2.jdbc-url=jdbc:postgresql://localhost:5433/postgres
spring.datasource.db2.driver-class-name=org.postgresql.Driver
spring.datasource.db2.username=postgres
spring.datasource.db2.password=root

# JPA Settings
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true